- name: "Add Node.js from node source"
  become: true
  shell: |
   curl -fsSL https://deb.nodesource.com/setup_13.x | sudo -E bash -
  #  sudo apt install -y nodejs
  
- name: " Install Node.js 13"
  become: true
  apt: 
    name: ["nodejs"]
    state: latest
    update_cache: yes

- name: "Install PM2 Globallyl"
  npm: 
    name: pm2
    global: yes
